In [6]:
import soccerdata as sd
import warnings

# The use of warnings filters ensures that deprecation and future warnings do not clutter the output.
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

### Overview: 

The code in this notebook demonstrates how to use the `soccerdata` library to fetch football data from FBref. It initializes the FBref object for the English Premier League across multiple seasons, retrieves team match statistics for Chelsea, fetches lineups for a specific match, and obtains event data for that match.

To explore the `soccerdata` library further, visit https://soccerdata.readthedocs.io/en/latest/datasources/FBref.html

### Create an instance of FBRef


Necessary data for the league and seasons specified will be downloaded and cached locally in ``~/soccerdata/data/FBref``

Each call from this class will provide a ``pd.DataFrames`` object for data from http://fbref.com.

This data can then be saved to a database or file for further analysis

In [7]:
fbref = sd.FBref(leagues="ENG-Premier League", seasons=[20, 21, 22, 23, 24, 25])

[20/08/2026 20:00:59] INFO     Saving cached data to C:\Users\mwanz\soccerdata\data\FBref            _common.py:250

### Get match statistics for a specific team

Here I am getting the match statistics for Chelsea in the Premier League for the seasons 2020-2026.  The `stat_type` parameter is set to "schedule" to get the match schedule and results for the team.

We get details such as:
- the opponent and match result
- numbers of goals scored
- kick-off time and date of the match
- ball possesion of the team in question

In the ``match_report`` field, we have entries of the form `/en/matches/{match_id}/{home team}-{away team}-{match date}-{league}`. From this, can extract the match id which can then be used to extract further statistics from a given match such as the lineups and match events.

For the first entry in the data frame (Brighton-Chelsea), we have `match_id = "9d7641eb"`. We use this to extract lineups and match events from this game.

In [3]:
team_match_stats = fbref.read_team_match_stats(stat_type="schedule", team="Chelsea")
team_match_stats.head()

                                                                          date  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea       2020-09-14
                                  2020-09-20 Chelsea-Liverpool      2020-09-20
                                  2020-09-26 West Brom-Chelsea      2020-09-26
                                  2020-10-03 Chelsea-Crystal Palace 2020-10-03
                                  2020-10-17 Chelsea-Southampton    2020-10-17

                                                                         time  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        20:15:00
                                  2020-09-20 Chelsea-Liverpool       16:30:00
                                  2020-09-26 West Brom-Chelsea       17:30:00
                                  2020-10-03 Chelsea-Crystal Palace  12:30:00
                                  2020-10-17 Chelsea-Southampton     15:00:00

                                                                           round  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        Matchweek 1
                                  2020-09-20 Chelsea-Liverpool       Matchweek 2
                                  2020-09-26 West Brom-Chelsea       Matchweek 3
                                  2020-10-03 Chelsea-Crystal Palace  Matchweek 4
                                  2020-10-17 Chelsea-Southampton     Matchweek 5

                                                                     day  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        Mon
                                  2020-09-20 Chelsea-Liverpool       Sun
                                  2020-09-26 West Brom-Chelsea       Sat
                                  2020-10-03 Chelsea-Crystal Palace  Sat
                                  2020-10-17 Chelsea-Southampton     Sat

                                                                    venue  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        Away
                                  2020-09-20 Chelsea-Liverpool       Home
                                  2020-09-26 West Brom-Chelsea       Away
                                  2020-10-03 Chelsea-Crystal Palace  Home
                                  2020-10-17 Chelsea-Southampton     Home

                                                                    result GF  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea            W  3
                                  2020-09-20 Chelsea-Liverpool           L  0
                                  2020-09-26 West Brom-Chelsea           D  3
                                  2020-10-03 Chelsea-Crystal Palace      W  4
                                  2020-10-17 Chelsea-Southampton         D  3

                                                                    GA  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        1
                                  2020-09-20 Chelsea-Liverpool       2
                                  2020-09-26 West Brom-Chelsea       3
                                  2020-10-03 Chelsea-Crystal Palace  0
                                  2020-10-17 Chelsea-Southampton     3

                                                                           opponent  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea              Brighton
                                  2020-09-20 Chelsea-Liverpool            Liverpool
                                  2020-09-26 West Brom-Chelsea            West Brom
                                  2020-10-03 Chelsea-Crystal Palace  Crystal Palace
                                  2020-10-17 Chelsea-Southampton        Southampton

                                                                     Poss  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea          48
                                  2020-09-20 Chelsea-Liverpool         39
                                  2020-09-26 West Brom-Chelsea         76
                                  2020-10-03 Chelsea-Crystal Palace    71
                                  2020-10-17 Chelsea-Southampton       53

                                                                     Attendance  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea              <NA>
                                  2020-09-20 Chelsea-Liverpool             <NA>
                                  2020-09-26 West Brom-Chelsea             <NA>
                                  2020-10-03 Chelsea-Crystal Palace        <NA>
                                  2020-10-17 Chelsea-Southampton           <NA>

                                                                               Captain  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea                 Jorginho
                                  2020-09-20 Chelsea-Liverpool                Jorginho
                                  2020-09-26 West Brom-Chelsea            Thiago Silva
                                  2020-10-03 Chelsea-Crystal Palace  César Azpilicueta
                                  2020-10-17 Chelsea-Southampton     César Azpilicueta

                                                                    Formation  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea         4-2-2-2
                                  2020-09-20 Chelsea-Liverpool          4-3-3
                                  2020-09-26 West Brom-Chelsea        4-2-3-1
                                  2020-10-03 Chelsea-Crystal Palace   4-2-3-1
                                  2020-10-17 Chelsea-Southampton      4-2-3-1

                                                                    Opp Formation  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea               3-5-2
                                  2020-09-20 Chelsea-Liverpool              4-3-3
                                  2020-09-26 West Brom-Chelsea              5-4-1
                                  2020-10-03 Chelsea-Crystal Palace         4-4-2
                                  2020-10-17 Chelsea-Southampton            4-4-2

                                                                            Referee  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea          Craig Pawson
                                  2020-09-20 Chelsea-Liverpool         Paul Tierney
                                  2020-09-26 West Brom-Chelsea        Jonathan Moss
                                  2020-10-03 Chelsea-Crystal Palace  Michael Oliver
                                  2020-10-17 Chelsea-Southampton       Peter Bankes

                                                                                                          match_report  \
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        /en/matches/9d7641eb/Brighton-and-Hove-Albion-...
                                  2020-09-20 Chelsea-Liverpool       /en/matches/c64e5792/Chelsea-Liverpool-Septemb...
                                  2020-09-26 West Brom-Chelsea       /en/matches/d725a16c/West-Bromwich-Albion-Chel...
                                  2020-10-03 Chelsea-Crystal Palace  /en/matches/d97aa1b5/Chelsea-Crystal-Palace-Oc...
                                  2020-10-17 Chelsea-Southampton     /en/matches/9bd558f5/Chelsea-Southampton-Octob...

                                                                    Notes
league             season team    game
ENG-Premier League 2021   Chelsea 2020-09-14 Brighton-Chelsea        <NA>
                                  2020-09-20 Chelsea-Liverpool       <NA>
                                  2020-09-26 West Brom-Chelsea       <NA>
                                  2020-10-03 Chelsea-Crystal Palace  <NA>
                                  2020-10-17 Chelsea-Southampton     <NA>

#### Lineups

In the lineup data, we get the names of the players named in the lineup on the day, whether the player started the match or was a substitute, and how many minutes they played.

For example `Ben White` was a starter for Brighton and was played 90 minutes of the game

In [4]:
# lineups
match_lineups = fbref.read_lineup(match_id = "9d7641eb")
match_lineups.head()

[08/20/26 19:58:36] INFO     [1/1] Retrieving game with id=9d7641eb                                    fbref.py:854

                                                       jersey_number  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea              1
                          2020-09-14 Brighton-Chelsea              2
                          2020-09-14 Brighton-Chelsea              3
                          2020-09-14 Brighton-Chelsea              4
                          2020-09-14 Brighton-Chelsea              5

                                                              player  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea    Mathew Ryan
                          2020-09-14 Brighton-Chelsea  Tariq Lamptey
                          2020-09-14 Brighton-Chelsea      Ben White
                          2020-09-14 Brighton-Chelsea   Adam Webster
                          2020-09-14 Brighton-Chelsea     Lewis Dunk

                                                                         team  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion

                                                      is_starter position  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea       True       GK
                          2020-09-14 Brighton-Chelsea       True       RM
                          2020-09-14 Brighton-Chelsea       True       CB
                          2020-09-14 Brighton-Chelsea       True       CB
                          2020-09-14 Brighton-Chelsea       True       CB

                                                       minutes_played
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea              90
                          2020-09-14 Brighton-Chelsea              90
                          2020-09-14 Brighton-Chelsea              78
                          2020-09-14 Brighton-Chelsea              90
                          2020-09-14 Brighton-Chelsea              90

### Match Events

We extract match events which include:
- goal scored, the player who scored and assited the goal
- substitution, the player coming off and on
- player carded

In [5]:
events = fbref.read_events(match_id=["9d7641eb"])
events.head()

[08/20/26 19:58:40] INFO     [1/1] Retrieving game with id=9d7641eb                                    fbref.py:949

                                                                         team  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea                 Chelsea
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea  Brighton & Hove Albion
                          2020-09-14 Brighton-Chelsea                 Chelsea
                          2020-09-14 Brighton-Chelsea                 Chelsea

                                                      minute score  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea    23’   0:1
                          2020-09-14 Brighton-Chelsea    45’   0:1
                          2020-09-14 Brighton-Chelsea    54’   1:1
                          2020-09-14 Brighton-Chelsea    56’   1:2
                          2020-09-14 Brighton-Chelsea    61’   1:2

                                                                player1  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea          Jorginho
                          2020-09-14 Brighton-Chelsea    Aaron Connolly
                          2020-09-14 Brighton-Chelsea  Leandro Trossard
                          2020-09-14 Brighton-Chelsea       Reece James
                          2020-09-14 Brighton-Chelsea      Ross Barkley

                                                                  player2  \
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea                None
                          2020-09-14 Brighton-Chelsea        Adam Lallana
                          2020-09-14 Brighton-Chelsea       Tariq Lamptey
                          2020-09-14 Brighton-Chelsea            Jorginho
                          2020-09-14 Brighton-Chelsea  Ruben Loftus-Cheek

                                                          event_type
league             season game
ENG-Premier League 2021   2020-09-14 Brighton-Chelsea   penalty_goal
                          2020-09-14 Brighton-Chelsea  substitute_in
                          2020-09-14 Brighton-Chelsea           goal
                          2020-09-14 Brighton-Chelsea           goal
                          2020-09-14 Brighton-Chelsea  substitute_in

The three DataFrames in this notebook can form a relational database with the match ID extracted from `match_report`, such as `9d7641eb`, as the canonical unique key joining the three databases.

1. **`matches`**: one row per match. Store `match_id`, `league`, `season`, `game`, date, home team, away team, final score, and the original `match_report` URL.
2. **`lineups`**: one row per player selected for a match. Store `match_id`, team, player, starter status, position, and minutes played.
3. **`events`**: one row per event. Store `match_id`, team, minute, score, event type, `player1`, and `player2`.

With our database in hand, which can be used to perform further analysis such as:
- team form by season, 
- home versus away performance, 
- goals scored and conceded, 
- possession and formation comparisons, 
- starting-lineup stability, player minutes and substitute usage, 
- the relationship between substitutions and results, 
- goal timing, scoring responses, assists, cards, and event patterns by team or player. 

It can also support predictive features such as recent form, average possession, lineup continuity, and early-goal frequency, provided that features are calculated only from matches before the prediction being evaluated.

Key points to consider:
- `events`: generate `event_id` as the primary key, with `match_id` as a foreign key. Include an event sequence number because several events can occur in the same minute.
- Add unique constraints to prevent duplicate matches, lineup rows, and events.
- Normalize team and player names before loading. Ideally create separate `teams` and `players` tables with stable IDs, then use `team_id` and `player_id` in the three fact tables.